version: '3.3'

services:
  server:
    build: backend
    ports:
      - "8000:8082"
    depends_on:
      - bsuirdb
    networks:
      - bsuir-network
    restart: always
  bot:
    build: bot
    networks:
      - bsuir-network
    depends_on:
      - server
    restart: always

  news-parser:
    build: news-parser
    networks:
      - bsuir-network
    depends_on:
      - server
    volumes:
      - last-update:/data
    restart: always

  bsuirdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'bsuirapi'
      MYSQL_USER: 'bsuir'
      MYSQL_PASSWORD: '123321'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - bsuir-network
    ports:
      - '3309:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  last-update:
  keys:

networks:
  bsuir-network:
    driver: bridge
