version: '2'

services:
  server:
    build: backend
    ports:
      - "9000:8082"
    depends_on:
      - bsuirdb
    networks:
      - bsuir-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5
  bot:
    build: bot
    networks:
      - bsuir-network
    depends_on:
      server:
        condition: service_healthy
    restart: always

  news-parser:
    build: news-parser
    networks:
      - bsuir-network
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - last-update:/data
    restart: always

  bsuirdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'bsuirapi'
      MYSQL_USER: 'bsuir'
      MYSQL_PASSWORD: '123321'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - bsuir-network
    ports:
      - '3309:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  last-update:
  keys:

networks:
  bsuir-network:
    driver: bridge
