CREATE TABLE IF NOT EXISTS `auditoriums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `type` VARCHAR(250)  NOT NULL,
  `floor`  INT NOT NULL,
  `building` INT NOT NULL,

   PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auditorium` INT NOT NULL,
  `weeks` INT NOT NULL,
  `day` INT NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `group` VARCHAR(255) NOT NULL,

   PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `news_source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,

  PRIMARY KEY  (`id`),
  UNIQUE KEY (name, type)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `source_id` INT NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `loading_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `url` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,

  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) DEFAULT NULL,

  PRIMARY KEY  (`id`),
  UNIQUE (`token`)
) DEFAULT CHARSET=utf8;