CREATE TABLE IF NOT EXISTS `auditoriums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `type` VARCHAR(250)  NOT NULL,
  `floor`  INT NOT NULL,
  `building` INT NOT NULL,

   PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auditorium` INT NOT NULL,
  `weeks` INT NOT NULL,
  `day` INT NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `group` VARCHAR(255) NOT NULL,

   PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `news_source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,

  PRIMARY KEY  (`id`),
  UNIQUE KEY (name, type)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `source_id` INT NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `loading_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `url` VARCHAR(255) NOT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,

  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) DEFAULT NULL,

  PRIMARY KEY  (`id`),
  UNIQUE (`token`)

) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `users` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `login` VARCHAR(255) NOT NULL,
   `password` VARCHAR(512) NOT NULL,

   PRIMARY KEY (`id`),
   UNIQUE (`login`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `files` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `user_id` INT NOT NULL,
   `filename` VARCHAR(255) NOT NULL,
   `fileId` VARCHAR(255) NOT NULL,
   `access_type` VARCHAR(125) NOT NULL,
   `group_owner` VARCHAR(125) NOT NULL,
   `file_type` VARCHAR(24) NOT NULL,
   `link` VARCHAR(255) DEFAULT NULL,
   `parent` INT DEFAULT NULL,


   PRIMARY KEY (`id`),
   UNIQUE (`fileId`)
) DEFAULT CHARSET=utf8;